Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Style/NumericPredicate:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $curbuf

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/LineLength:
  Max: 200

Style/RedundantReturn:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/RescueException:
  Enabled: false
